name: scm_engenharia_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  connectivity: ^2.0.1
  path_provider: ^1.6.22
  intl: ^0.16.1
  shared_preferences: ^0.5.12+2
  device_info: ^0.4.2+9
  jaguar_jwt: ^2.1.6
  hive: ^1.4.4+1
  sqflite: ^1.3.2+1
  flutter_open_whatsapp: ^0.1.2
  url_launcher: ^5.7.8
  month_picker_dialog: ^0.3.3
  autocomplete_textfield: ^1.7.3
  firebase_core: ^0.5.2
  firebase_messaging: ^7.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login_logo.png # logo negativa em branco
    - assets/ic_whatsapp.png
    - assets/img_error.png
    - assets/img_integracao.png
    - assets/img_sem_sinal.png
    - assets/img_informacao.png


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: avenir-next-rounded-pro-bold
      fonts:
        - asset: assets/fonts/avenir_next/avenir-next-rounded-pro-bold.ttf
    # -------------------------------------------------------------------------------
    - family: avenir-next-rounded-pro-bold-lt
      fonts:
        - asset: assets/fonts/avenir_next/avenir-next-rounded-pro-bold-lt.ttf
    # -------------------------------------------------------------------------------
    - family: avenir-next-rounded-pro-demi
      fonts:
        - asset: assets/fonts/avenir_next/avenir-next-rounded-pro-demi.ttf
    # -------------------------------------------------------------------------------
    - family: avenir-next-rounded-pro-demi-lt
      fonts:
        - asset: assets/fonts/avenir_next/avenir-next-rounded-pro-demi-lt.ttf
    # -------------------------------------------------------------------------------
    - family: avenir-next-rounded-pro-medium
      fonts:
        - asset: assets/fonts/avenir_next/avenir-next-rounded-pro-medium.ttf
    # -------------------------------------------------------------------------------
    - family: avenir-next-rounded-pro-medium-lt
      fonts:
        - asset: assets/fonts/avenir_next/avenir-next-rounded-pro-medium-lt.ttf
    # -------------------------------------------------------------------------------
    - family: avenir-next-rounded-pro-regular
      fonts:
        - asset: assets/fonts/avenir_next/avenir-next-rounded-pro-regular.ttf
    # -------------------------------------------------------------------------------
    - family: avenir-next-rounded-pro-regular-lt
      fonts:
        - asset: assets/fonts/avenir_next/avenir-next-rounded-pro-regular-lt.ttf


    # -------------------------------------------------------------------------------
    - family: avenir-lt-std-book
      fonts:
        - asset: assets/fonts/avenir_lt/avenir-lt-std-book.otf
    # -------------------------------------------------------------------------------
    - family: avenir-lt-std-book-oblique
      fonts:
        - asset: assets/fonts/avenir_lt/avenir-lt-std-book-oblique.otf
    # -------------------------------------------------------------------------------
    - family: avenir-lt-std-light
      fonts:
        - asset: assets/fonts/avenir_lt/avenir-lt-std-light.otf
    # -------------------------------------------------------------------------------
    - family: avenir-lt-std-light-oblique
      fonts:
        - asset: assets/fonts/avenir_lt/avenir-lt-std-light-oblique.otf
    # -------------------------------------------------------------------------------
    - family: avenir-lt-std-medium
      fonts:
        - asset: assets/fonts/avenir_lt/avenir-lt-std-medium.otf
    # -------------------------------------------------------------------------------
    - family: avenir-lt-std-medium-oblique
      fonts:
        - asset: assets/fonts/avenir_lt/avenir-lt-std-medium-oblique.otf
    # -------------------------------------------------------------------------------
    - family: avenir-lt-std-oblique
      fonts:
        - asset: assets/fonts/avenir_lt/avenir-lt-std-oblique.otf
    # -------------------------------------------------------------------------------
    - family: avenir-lt-std-roman
      fonts:
        - asset: assets/fonts/avenir_lt/avenir-lt-std-roman.otf
    # -------------------------------------------------------------------------------



    - family: open-sans-bold
      fonts:
        - asset: assets/fonts/open_sans/open-sans-bold.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-bold-italic
      fonts:
        - asset: assets/fonts/open_sans/open-sans-bold-italic.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-extra-bold
      fonts:
        - asset: assets/fonts/open_sans/open-sans-extra-bold.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-extra-bold-italic
      fonts:
        - asset: assets/fonts/open_sans/open-sans-extra-bold-italic.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-italic
      fonts:
        - asset: assets/fonts/open_sans/open-sans-italic.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-light
      fonts:
        - asset: assets/fonts/open_sans/open-sans-light.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-light-italic
      fonts:
        - asset: assets/fonts/open_sans/open-sans-light-italic.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-regular
      fonts:
        - asset: assets/fonts/open_sans/open-sans-regular.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-semi-bold
      fonts:
        - asset: assets/fonts/open_sans/open-sans-semi-bold.ttf
    # -------------------------------------------------------------------------------
    - family: open-sans-semi-bold-italic
      fonts:
        - asset: assets/fonts/open_sans/open-sans-semi-bold-italic.ttf
    # -------------------------------------------------------------------------------
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
